### ISSUE TITLE
"About us" does not respect paragraphs

### ISSUE THREAD

**Issue by jan-martinek** [Demagog2/demagog#28]
(Just the first part right under the title.)

**Comment by vaclavbohac** [comment]
@jan-martinek It's caused by CSS forcing the `br` elements to have `display: none;` We could turn it off for the about us page. Do you agree?

<img width="478" alt="screen shot 2018-01-22 at 22 47 56" src="https://user-images.githubusercontent.com/139369/35246396-d6a0e8ea-ffc6-11e7-86ea-a27c52394eb8.png">

**Comment by jan-martinek** [comment]
Thanks for looking into this!

I checked it out and tried to come up with some sensible css (and a way of marking the article), but it might be enough just to add the paragraphs into the source text (instead of the `br` els that the MS Word→wysiwyg conversion created). Perhaps this should be enough for now. (I'll close it after the sucessful migration.)
